name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to simulate (e.g. v0.2.1)"
        required: false

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag and version
        id: vars
        run: |
          TAG=${{ github.event.release.tag_name || github.event.inputs.tag || 'v0.0.0' }}
          VERSION="${TAG#v}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download release asset
        run: |
          ASSET_URL="https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag }}/rdslink-macos.tar.gz"
          echo "asset_url=$ASSET_URL" >> $GITHUB_ENV
          curl -L "$ASSET_URL" -o rdslink-macos.tar.gz
          shasum -a 256 rdslink-macos.tar.gz | awk '{ print $1 }' > checksum.txt
          echo "sha256=$(cat checksum.txt)" >> $GITHUB_OUTPUT
        id: checksum

      - name: Clone homebrew tap
        uses: actions/checkout@v4
        with:
          repository: DenzoNL/homebrew-tap  # Replace with your actual tap repo
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: tap

      - name: Update formula
        run: |
          FORMULA="tap/Formula/rdslink.rb"
          TAG=${{ steps.vars.outputs.tag }}
          ASSET_URL="$asset_url"
          SHA256=${{ steps.checksum.outputs.sha256 }}

          # Replace URL and SHA256 in formula
          sed -i.bak -E "s|url \".*\"|url \"$ASSET_URL\"|" "$FORMULA"
          sed -i.bak -E "s|sha256 \".*\"|sha256 \"$SHA256\"|" "$FORMULA"
          rm "$FORMULA.bak"

      - name: Commit and push
        run: |
          cd tap
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Update rdslink formula to ${{ steps.vars.outputs.tag }}"
          git push
